feature-PF16
luisfelipe3d/projeto-formais pull request #11
Opened 2021-04-30 06:53 UTC by luisfelipe3d

adicionado tratamento de exceção no main
![image](https://user-images.githubusercontent.com/31942862/116659231-a6cb5080-a967-11eb-9ff6-61417df9bbd0.png)

2021-04-30 18:08 UTC, RodrigoMarianoLeal approved these changes

2021-04-30 18:20 UTC, loloca requested changes

2021-04-30 18:20 UTC, loloca commented on simulador_automato/src/main/controller/AFDControlador.java
> +    private final List<EF> AFD = new ArrayList();
Remover final.

2021-05-01 21:24 UTC, joaothalis approved these changes

2021-05-01 21:31 UTC, loloca approved these changes

2021-05-01 21:31 UTC, merged